///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BDD2.Recordings
{
    public partial class EnterNumber
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Key_sequence_Calculadora(RepoItemInfo windowsappInfo, string input)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Input' with focus on 'windowsappInfo'.", windowsappInfo);
            windowsappInfo.FindAdapter<WindowsApp>().EnsureVisible();
            Keyboard.Press(Input);
        }

        public void Mouse_Click_Screen(RepoItemInfo containerInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'containerInfo' at 173;22.", containerInfo);
            containerInfo.FindAdapter<Container>().Click("173;22");
        }

    }
}
