///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BDD2.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateScreen recording.
    /// </summary>
    [TestModule("41b59cb9-136b-498f-917e-74a7979e4663", ModuleType.Recording, 1)]
    public partial class ValidateScreen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::BDD2.BDD2Repository repository.
        /// </summary>
        public static global::BDD2.BDD2Repository repo = global::BDD2.BDD2Repository.Instance;

        static ValidateScreen instance = new ValidateScreen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateScreen()
        {
            ExpectedResult = "100";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateScreen Instance
        {
            get { return instance; }
        }

#region Variables

        string _ExpectedResult;

        /// <summary>
        /// Gets or sets the value of variable ExpectedResult.
        /// </summary>
        [TestVariable("3d08d180-ed6a-491d-b7f1-14b54f7f2856")]
        public string ExpectedResult
        {
            get { return _ExpectedResult; }
            set { _ExpectedResult = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            ValidateScreenValue(repo.Calculadora.ScreenInfo, ExpectedResult);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
